### ISSUE TITLE
Add a switch to change the miner between TeamBlackMiner & TeamRedMiner.

### ISSUE THREAD

**Issue by aplace-lab** [aplace-lab/amber-kawpow-miner#9]
Also, please add a switch to change the miner selection between TeamBlackMiner & TeamRedMiner.

_Originally posted by @Cyclic-TP in https://github.com/aplace-lab/amber-kawpow-miner/issues/2#issuecomment-2387588112_

**Comment by aplace-lab** [comment]
@Cyclic-TP This is likely easier to implement if I assert that all Nvidia cards use TBM, and all AMD cards use TRM. Do you see a use-case where being able to explicitly select the mining executable for individual cards is necessary?

**Comment by Cyclic-TP** [comment]
@aplace-lab I see this as a rig-level feature only, not for individual GPU's within a rig. It will let me make AMD only rigs and get the best hash rates. Any mixed GPU rig will be fine on TBM.

**Comment by aplace-lab** [comment]
This is now solved in #12
